#####  hotkey definition #####
#keycodes works only on my computer, i haven't checked them on other systems, and i dont recognize this codes as any standart.
#delete is default key with 211 code.
#num1-num3 is 79-81 
#num4-num6 is 75-78
#num7-num9 is 71-73

levels: "0,1,2,3,4,5,6,7"
##############################
#### delete tiles funtion ####
##############################
Dkey: 71

#specify levels comma separated;
#affected radius, 15 means a 31x31 square around player will be affected

radius: 15          

# object.spritename:"carpentry_01_16", spriteid: 20000000 - example of properties for cheatbox.

tilesToRemoveList:
  - spriteID: 2000000
    object.spritename: "carpentry_01_16"
  - spriteID: 226028
    object.spritename: ""
    sprite.name: "fixtures_doors_fences_01_28"
  - sprite.name: "fixtures_doors_fences_01_29"

#can be specified multiple objects, or single one ("-") entry;
#object.spritename, sprite.name, spriteID fields are recognized for object;
#one or multiple field must be specified for each object.




#############################n
#### restore floors func ####
#############################  
Fkey: 72

#only specified tiles will be affected. same format as list described above;
floorList: 
  - sprite.name: "carpentry_02_56"

##############################
#### restore objects func ####
##############################  
Rkey: 73

##############################
####    Lock Containers   ####
##############################  
Ckey: 75
