#####  hotkey definition #####
hotkey: 211 
#delete is default key with 211 code.

##############################
#### delete tiles funtion ####
##############################

#true/false - enabled/disabled
deleteTiles: true  

#affected radius, 15 means a 31x31 square around player will be affected
radius: 15          

# object.spritename:"carpentry_01_16", spriteid: 2000000 - example of properties for cheatbox.

tilesToRemoveList:
  - sprite.name: "fixtures_doors_fences_01_28"
  - sprite.name: "fixtures_doors_fences_01_29"

#object.spritename, sprite.name, spriteID fields are recognized;

#example of unused here list with multiple objects specified:
unusedList:
  - spriteID: 2000000
    object.spritename: "carpentry_01_16"
  - spriteID: 226028
    object.spritename: ""
    sprite.name: "fixtures_doors_fences_01_28"
  - sprite.name: "fixtures_doors_fences_01_29"

#all can be specified to delete everything (will work skipping floors to avoid troubles):
unusedList2:
  - "all"


#############################n
#### restore floors func ####
#############################

restoreFloors: true        
  
#only specified tiles will be affected. same format as list described above;
floorList: 
  #- sprite.name: "carpentry_02_56"
  - "all"

##############################
#### restore objects func ####
##############################
restoreOtherObjects: true    

### complex procedure to restore default objects in chunk, leaving untouched objects created by users;
### to achieve best results it is recomennded to clear chunk, to get 99.999% effective restore . . .